import React, { useEffect, useState } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { AuthService } from '../auth/authService';
import { AttendanceService } from './attendanceService';
import { getDb, getLocalDeviceSession, initializeDatabase } from '../database/localPersistence';
import { subscribeRepositoryChanges } from '../database/repositoryChangeBus';
import { DeviceRegistrationService } from '../identity/deviceRegistrationService';
import { IdentityService } from '../identity/identityService';
import type { ApplicationContext } from '../identity/projectContext';
import type { SyncRuntime } from '../sync/syncRuntime';
import type { SupabaseClient } from '@supabase/supabase-js';

type QaResult = { label: string; detail: string; passed: boolean };
const DATABASE_NAME = 'm17-real-runtime-device.db';
function nowUtc(): string { return new Date().toISOString(); }
function makeInstallationKey(): string { return `m17-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`; }
interface M17RealRuntimeQaScreenProps { onBack: () => void; authService: AuthService; client: SupabaseClient; runtime: Pick<SyncRuntime, 'start' | 'stop' | 'requestManualSync'>; }

export function M17RealRuntimeQaScreen({ onBack, authService, client, runtime }: M17RealRuntimeQaScreenProps) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [context, setContext] = useState<ApplicationContext | null>(null); const [running, setRunning] = useState(false); const [results, setResults] = useState<QaResult[]>([]); const [status, setStatus] = useState('Database initialising…'); const [localState, setLocalState] = useState('No local attendance state loaded'); const [observedAt, setObservedAt] = useState<string | null>(null);
  const refreshLocalState = async () => { try { const db = getDb(); const result = await db.execute(`SELECT s.state, s.current_revision, s.server_revision, s.sync_status, (SELECT COUNT(*) FROM command_ledger c WHERE c.project_id = s.project_id AND c.person_id = s.person_id AND c.status = 'PENDING') AS pending_commands FROM attendance_state s ORDER BY s.updated_at DESC LIMIT 1`); if (result.rows.length === 0) { setLocalState('No attendance state'); return; } const row = result.rows.item(0) as Record<string, unknown>; setLocalState(`${String(row.state)} · local rev ${String(row.current_revision)} · server rev ${String(row.server_revision ?? 'null')} · ${String(row.sync_status)} · pending ${String(row.pending_commands)}`); } catch (error) { setLocalState(error instanceof Error ? error.message : String(error)); } };
  useEffect(() => { const unsubscribe = subscribeRepositoryChanges(event => { setObservedAt(event.at); setStatus(`REPOSITORY OBSERVER · ${event.kind.toUpperCase()} CHANGE RECEIVED`); void refreshLocalState(); }); void initializeDatabase(DATABASE_NAME).then(async () => { await refreshLocalState(); setStatus('READY — isolated M1.7 runtime QA'); }).catch(error => { setStatus(error instanceof Error ? error.message : String(error)); }); return () => { unsubscribe(); void runtime.stop(); }; }, [runtime]);
  const login = async () => { setRunning(true); setStatus('Authenticating against isolated Supabase…'); try { const session = await authService.signIn(email.trim(), password); const identity = await new IdentityService(client).resolve(session.user.id); if (identity.projectAssignments.length === 0) throw new Error('Authenticated user has no active project assignment'); let installation = await new DeviceRegistrationService(client).get(session.user.id); const localDevice = await getLocalDeviceSession(session.user.id); if (!installation || installation.status !== 'ACTIVE') { installation = await new DeviceRegistrationService(client).register(session.user.id, { installationKey: localDevice?.installationKey ?? makeInstallationKey(), deviceName: 'M1.7 PHYSICAL QA DEVICE', appVersion: 'M1.7-QA', osVersion: String(Platform.Version), now: nowUtc() }); } if (installation.status !== 'ACTIVE') throw new Error('Authoritative device installation is REVOKED'); const resolved = await new IdentityService(client).resolve(session.user.id); const activeAssignment = resolved.projectAssignments.find(a => a.status === 'ACTIVE'); if (!activeAssignment) throw new Error('No active project assignment after device registration'); setContext({ userId: resolved.userId, profile: resolved.profile, person: resolved.person, organisation: resolved.organisation, memberships: resolved.memberships, activeProjectAssignments: resolved.projectAssignments, hasProjectAccess: true, device: installation }); setStatus(`AUTHENTICATED · ${resolved.person.displayName} · ${activeAssignment.projectId}`); setResults([{ label: 'Authenticated application context', detail: 'Real Supabase session + authoritative identity + active device', passed: true }]); await runtime.start(); await refreshLocalState(); } catch (error) { setResults([{ label: 'Authentication/context', detail: error instanceof Error ? error.message : String(error), passed: false }]); setStatus('AUTHENTICATION FAILED'); } finally { setRunning(false); } };
  const createOfflineCheckIn = async () => { if (!context) { setStatus('Authenticate first'); return; } const assignment = context.activeProjectAssignments[0]; setRunning(true); try { const mutation = await AttendanceService.checkIn({ context, projectId: assignment.projectId, targetPersonId: context.person.id, targetAssignment: assignment, source: 'SELF', clientOccurredAt: nowUtc(), online: false }); setResults(previous => [...previous, { label: 'Offline durable check-in', detail: `${mutation.command.commandId} · ${mutation.state.syncStatus} · local revision ${mutation.state.currentRevision}`, passed: mutation.command.status === 'PENDING' && mutation.state.syncStatus === 'OFFLINE_PENDING_VERIFICATION' }]); setStatus('OFFLINE COMMAND PERSISTED — SAFE TO KILL/RESTART APP NOW'); await refreshLocalState(); } catch (error) { setResults(previous => [...previous, { label: 'Offline durable check-in', detail: error instanceof Error ? error.message : String(error), passed: false }]); setStatus('OFFLINE CHECK-IN FAILED'); } finally { setRunning(false); } };
  const syncPending = async () => { if (!context) { setStatus('Authenticate first'); return; } setRunning(true); setStatus('Submitting pending command through real RPC…'); try { await runtime.start(); const result = await runtime.requestManualSync(); const passed = result.status === 'SUCCEEDED'; setResults(previous => [...previous, { label: 'Real Supabase reconciliation', detail: JSON.stringify(result), passed }]); setStatus(passed ? 'AUTHORITATIVE STATE RECONCILED INTO SQLITE' : 'SYNC DID NOT SUCCEED'); await refreshLocalState(); } catch (error) { setResults(previous => [...previous, { label: 'Real Supabase reconciliation', detail: error instanceof Error ? error.message : String(error), passed: false }]); setStatus('SYNC FAILED'); } finally { setRunning(false); } };
  const signOut = async () => { await runtime.stop(); await authService.signOut(); setContext(null); setStatus('SIGNED OUT'); await refreshLocalState(); };
  const passed = results.filter(result => result.passed).length;
  return (<ScrollView contentContainerStyle={styles.container}><View style={styles.header}><Pressable onPress={onBack} hitSlop={12}><Text style={styles.back}>‹ BACK</Text></Pressable><Text style={styles.label}>M1.7 PHYSICAL QA</Text></View><Text style={styles.eyebrow}>SITE-SYNC</Text><Text style={styles.title}>REAL RUNTIME</Text><Text style={styles.subtitle}>Isolated Supabase → authenticated RPC → durable SQLite reconciliation.</Text><View style={styles.warning}><Text style={styles.warningTitle}>TEST PROJECT ONLY</Text><Text style={styles.warningBody}>This harness is hard-wired to the isolated M1.7 project. It contains no production URL, credential, or service-role key.</Text></View>{!context && (<View style={styles.card}><Text style={styles.cardTitle}>AUTHENTICATE</Text><TextInput autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Test account email" placeholderTextColor="#8A94A8" style={styles.input} /><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Test account password" placeholderTextColor="#8A94A8" style={styles.input} /><Pressable style={styles.primary} disabled={running || !email || !password} onPress={login}><Text style={styles.primaryText}>{running ? 'AUTHENTICATING…' : 'SIGN IN TO ISOLATED PROJECT'}</Text></Pressable></View>)}{context && (<View style={styles.card}><Text style={styles.cardTitle}>AUTHENTICATED</Text><Text style={styles.identity}>{context.person.displayName}</Text><Text style={styles.detail}>{context.organisation.name} · {context.activeProjectAssignments[0]?.projectId}</Text><Pressable style={styles.primary} disabled={running} onPress={createOfflineCheckIn}><Text style={styles.primaryText}>CREATE OFFLINE CHECK-IN</Text></Pressable><Pressable style={styles.secondary} disabled={running} onPress={syncPending}><Text style={styles.secondaryText}>SYNC PENDING COMMAND</Text></Pressable><Pressable style={styles.tertiary} disabled={running} onPress={signOut}><Text style={styles.tertiaryText}>SIGN OUT</Text></Pressable></View>)}<View style={styles.card}><Text style={styles.cardTitle}>REPOSITORY-DRIVEN OBSERVATION</Text><Text style={styles.local}>{localState}</Text><Text style={styles.status}>{status}</Text>{observedAt && <Text style={styles.detail}>Last repository event: {observedAt}</Text>}</View>{results.length > 0 && (<View style={styles.card}><Text style={styles.summary}>{passed}/{results.length} OBSERVATIONS PASSED</Text>{results.map((result, index) => (<View key={`${result.label}-${index}`} style={styles.row}><View style={[styles.dot, result.passed ? styles.pass : styles.fail]} /><View style={styles.copy}><Text style={styles.name}>{result.label}</Text><Text style={styles.detail}>{result.detail}</Text></View></View>))}</View>)}</ScrollView>);
}
const styles = StyleSheet.create({ container: { padding: 24, paddingBottom: 48, backgroundColor: '#F4F6FA', minHeight: '100%' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, back: { color: '#0D1733', fontSize: 11, fontWeight: '900', letterSpacing: 1 }, label: { color: '#65718A', fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, eyebrow: { color: '#65718A', fontSize: 11, fontWeight: '900', letterSpacing: 2 }, title: { marginTop: 4, color: '#0D1733', fontSize: 30, fontWeight: '900' }, subtitle: { marginTop: 6, color: '#59657D', fontSize: 14, lineHeight: 20 }, warning: { marginTop: 22, padding: 16, borderRadius: 16, backgroundColor: '#FFF4D8', borderWidth: 1, borderColor: '#E9C46A' }, warningTitle: { color: '#6B4C00', fontSize: 11, fontWeight: '900', letterSpacing: 1 }, warningBody: { marginTop: 6, color: '#735B1C', fontSize: 12, lineHeight: 18 }, card: { marginTop: 16, padding: 18, borderRadius: 20, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE2EF' }, cardTitle: { color: '#0D1733', fontSize: 12, fontWeight: '900', letterSpacing: 1 }, input: { marginTop: 12, borderWidth: 1, borderColor: '#CBD3E3', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, color: '#0D1733', backgroundColor: '#F8F9FC' }, primary: { marginTop: 14, borderRadius: 14, paddingVertical: 15, alignItems: 'center', backgroundColor: '#0D1733' }, primaryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900', letterSpacing: 1 }, secondary: { marginTop: 10, borderRadius: 14, paddingVertical: 15, alignItems: 'center', backgroundColor: '#F3B33D' }, secondaryText: { color: '#0D1733', fontSize: 11, fontWeight: '900', letterSpacing: 1 }, tertiary: { marginTop: 10, paddingVertical: 10, alignItems: 'center' }, tertiaryText: { color: '#65718A', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, identity: { marginTop: 8, color: '#0D1733', fontSize: 20, fontWeight: '900' }, detail: { marginTop: 4, color: '#65718A', fontSize: 11, lineHeight: 16 }, local: { marginTop: 10, color: '#0D1733', fontSize: 12, lineHeight: 18, fontWeight: '700' }, status: { marginTop: 8, color: '#65718A', fontSize: 11, lineHeight: 16 }, summary: { color: '#0D1733', fontSize: 16, fontWeight: '900' }, row: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#E8ECF4', marginTop: 8 }, dot: { width: 10, height: 10, borderRadius: 5, marginTop: 5 }, pass: { backgroundColor: '#36A269' }, fail: { backgroundColor: '#C84D4D' }, copy: { flex: 1, marginLeft: 12 }, name: { color: '#0D1733', fontSize: 12, fontWeight: '800' } });
